-- vim.pack.add ({
--   'https://github.com/mfussenegger/nvim-dap'
--   'https://github.com/rcarriga/nvim-dap-ui',
--   'https://github.com/nvim-neotest/nvim-nio',
-- }),
-- local dap = require("dap")
--
-- vim.keymap.set("n", "<Leader>dt", ":DapToggleBreakpoint<CR>")
-- vim.keymap.set("n", "<Leader>dc", ":DapContinue<CR>")
-- vim.keymap.set("n", "<Leader>dx", ":DapTerminate<CR>")
-- vim.keymap.set("n", "<Leader>do", ":DapStepOver<CR>")
--
-- -- Adapter configurations
-- dap.adapters.cppdbg = {
--   id = "cppdbg",
--   type = "executable",
--   command = "/home/fern-snow/.local/share/nvim/mason/packages/cpptools/extension/debugAdapters/bin/OpenDebugAD7",
-- }
-- dap.configurations.cpp = {
--   {
--     name = "Launch file",
--     type = "cppdbg",
--     request = "launch",
--     program = function()
--       return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
--     end,
--     cwd = "${workspaceFolder}",
--     stopAtEntry = true,
--   },
--   {
--     name = "Attach to gdbserver :1234",
--     type = "cppdbg",
--     request = "launch",
--     MIMode = "gdb",
--     miDebuggerServerAddress = "localhost:1234",
--     miDebuggerPath = "/usr/bin/gdb",
--     cwd = "${workspaceFolder}",
--     program = function()
--       return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
--     end,
--   },
-- }
-- dap.configurations.c = dap.configurations.cpp
-- dap.configurations.rust = dap.configurations.cpp
-- local dap, dapui = require("dap"), require("dapui")
-- dap.listeners.before.attach.dapui_config = function()
--   dapui.open()
-- end
-- dap.listeners.before.launch.dapui_config = function()
--   dapui.open()
-- end
-- dap.listeners.before.event_terminated.dapui_config = function()
--   dapui.close()
-- end
-- dap.listeners.before.event_exited.dapui_config = function()
--   dapui.close()
-- end
-- require("dapui").setup()
