preload = /home/fern-snow/Documents/t-5-1-1.png
preload = /home/fern-snow/Documents/t-5-1-2.png
wallpaper = DP-1, /home/fern-snow/Documents/t-5-1-1.png
wallpaper = DP-2, /home/fern-snow/Documents/t-5-1-2.png