styles = {
    'advent-of-code.css': ['*adventofcode.com*'],
    'alacritty.org.css': ['*alacritty.org*'],
    'alternativeto.css': ['*alternativeto.net*', '*auth.alternativeto.net*'],
    'amplenote.css': ['*amplenote.com*'],
    'anilist.css': ['*anilist.co*', '*anichart.net*', '*anichart.net*'],
    'anonymous-overflow.css': ['*ao.vern.cc*', '*overflow.adminforge.de*', '*overflow.floppa.cloud*', '*overflow.hostux.net*', '*ao.bloat.cat*', '*ao.owo.si*', '*overflow.r4fo.com*', '*overflow.ducks.party*', '*anonymousoverflow.privacyredirect.com*', '*soflow.nerdvpn.de*', '*overflow.einfachzocken.eu*', '*anonymousoverflow.catsarch.com*', '*overflow.darkness.services*', '*anonflow.aketawi.space*', '*o.iii.st*', '*overflow.canine.tools*'],
    'arch-wiki.css': ['*wiki.archlinux.org*'],
    'boringproxy.css': ['*boring.example.com*'],
    'brave-search.css': ['*search.brave.com*'],
    'bsky.css': ['*bsky.app*'],
    'bstats.css': ['*bstats.org*'],
    'canvas-lms.css': ['*instructure.com*', '*instructuremedia.com*'],
    'chatgpt.css': ['*chatgpt.com*', '*auth.openai.com*'],
    'chatreplay.css': ['*chatreplay.stream*'],
    'chess.com.css': ['*chess.com*'],
    'cinny.css': ['*cinny.in*'],
    'claude.css': ['*claude.ai*'],
    'cobalt.css': ['*cobalt.tools*'],
    'codeberg.css': ['*codeberg.org*', '*codeberg.org*'],
    'crates.io.css': ['*crates.io*'],
    'crowdin.css': [r'https://crowdin.com(?!/translate).*', r'https://crowdin.com/translate/.*'],
    'deepl.css': [r'https:\\/\\/www.deepl.com\\/?(.*\\/)translator.*$'],
    'deepseek.css': ['https://chat.deepseek.com*'],
    'desmos.css': [r'^(https?:\/\/)(?!(cl|teacher|student)\.desmos\.com)([a-zA-Z0-9-]+\.)?desmos\.com(\/.*)?$'],
    'dev.to.css': ['*dev.to*', '*forem.com*'],
    'devdocs.css': ['*devdocs.io*'],
    'docs.deno.com.css': ['*docs.deno.com*'],
    'docs.rs.css': ['*docs.rs*', '*doc.rust-lang.org*'],
    'duckduckgo.css': ['*duckduckgo.com*', '*duck.ai*', '*start.duckduckgo.com*'],
    'ecosia.css': ['*ecosia.org*'],
    'elk.css': ['*elk.zone*'],
    'formative.css': ['*app.formative.com*', '*goformative.com*'],
    'freedesktop.css': ['*www.freedesktop.org*', '*specifications.freedesktop.org*'],
    'ghostty.org.css': ['*ghostty.org*'],
    'github.css': ['*gist.github.com*', '*docs.github.com*', '*viewscreen.githubusercontent.com*', r'https:\/\/github\.com(?!(\/home$|\/features($|\/.*)|\/organizations\/plan)).*$', r'https:\/\/notebooks\.githubusercontent\.com\/view\/ipynb.*'],
    'gleam.run.css': ['*gleam.run*'],
    'gmail.css': ['*mail.google.com*'],
    'go.dev.css': ['*go.dev*', '*pkg.go.dev*', 'https://go.dev/tour*'],
    'google.css': [r'^https?://(www\\.|images\\.)?google\\..*', r'^https?://(ogs\\.)?google\\..*'],
    'google-drive.css': ['*drive.google.com*'],
    'google-gemini.css': ['*gemini.google.com*'],
    'google-photos.css': ['*photos.google.com*'],
    'grabify.css': ['*grabify.link*'],
    'graphite.css': ['*app.graphite.com*'],
    'hackage.css': ['*hackage.haskell.org*', '*hackage-content.haskell.org*'],
    'hacker-news.css': ['*news.ycombinator.com*'],
    'hardcover.css': ['https://hardcover.app*', 'https://staging.hardcover.app*'],
    'have-i-been-pwned.css': ['*haveibeenpwned.com*'],
    'holodex.css': ['*holodex.net*'],
    'home-manager-options-search.css': ['*home-manager-options.extranix.com*'],
    'homepage.css': ['*homepage.example.com*', r'https?://homepage\\..*'],
    'hoogle.css': ['*hoogle.haskell.org*'],
    'hoppscotch.css': ['*hoppscotch.io*'],
    'hyperpipe.css': ['*hyperpipe.surge.sh*'],
    'ichi.moe.css': ['*ichi.moe*'],
    'indie-wiki-buddy.css': ['*bing.com*', '*search.brave.com*', '*duckduckgo.com*', '*ecosia.org*', '*kagi.com*', '*qwant.com*', '*search.yahoo.com*', '*startpage.com*', '*ya.ru*', '*fandom.com*', '*fextralife.com*', '*neoseeker.com*', '*breezewiki.com*', '*antifandom.com*', '*bw.artemislena.eu*', '*breezewiki.catsarch.com*', '*breezewiki.esmailelbob.xyz*', '*breezewiki.frontendfriendly.xyz*', '*bw.hamstro.dev*', '*breeze.hostux.net*', '*breezewiki.hyperreal.coffee*', '*breeze.mint.lgbt*', '*breezewiki.nadeko.net*', '*nerd.whatever.social*', '*breeze.nohost.network*', '*z.opnxng.com*', '*bw.projectsegfau.lt*', '*breezewiki.pussthecat.org*', '*bw.vern.cc*', '*breeze.whateveritworks.org*', '*breezewiki.woodland.cafe*', r'^https?://(www\\.)?google\\..*', r'^https?://(www\\.)?yandex\\..*'],
    'inoreader.css': ['*inoreader.com*'],
    'instagram.css': ['*instagram.com*', r'^.*instagram.com/direct.*'],
    'invidious.css': ['*anontube.lvkaszus.pl*', '*inv.citw.lgbt*', '*inv.in.projectsegfau.lt*', '*inv.tux.pizza*', '*inv.us.projectsegfau.lt*', '*inv.zzls.xyz*', '*invidious.asir.dev*', '*invidious.drgns.space*', '*invidious.einfachzocken.eu*', '*invidious.fdn.fr*', '*invidious.io.lol*', '*invidious.lunar.icu*', '*invidious.nerdvpn.de*', '*invidious.no-logs.com*', '*invidious.perennialte.ch*', '*invidious.privacydev.net*', '*invidious.private.coffee*', '*invidious.projectsegfau.lt*', '*invidious.protokolla.fi*', '*invidious.slipfox.xyz*', '*iv.datura.network*', '*iv.ggtyler.dev*', '*iv.melmac.space*', '*iv.nboeck.de*', '*iv.winston.sh*', '*onion.tube*', '*vid.priv.au*', '*vid.puffyan.us*', '*yewtu.be*', '*yt.artemislena.eu*', '*yt.cdaut.de*', '*yt.drgnz.club*', '*yt.oelrichsgarcia.de*'],
    'invokeai.css': [r'http:\\/\\/(127\\.0\\.0\\.1|localhost):9090(.*)'],
    'jisho.css': ['*jisho.org*'],
    'keybr.com.css': ['*keybr.com*'],
    'keyoxide.css': ['*docs.keyoxide.org*', '*blog.keyoxide.org*', 'https://keyoxide.org*'],
    'lastfm.css': ['*last.fm*'],
    'learn-x-in-y-minutes.css': ['*learnxinyminutes.com*'],
    'lemmy.css': ['*lemmy.ml*', '*lemmy.world*'],
    'libreddit.css': ['*libredd.it*', '*libreddit.spike.codes*', '*libreddit.dothq.co*', '*libreddit.kavin.rocks*', '*reddit.invak.id*', '*reddit.phii.me*', '*lr.riverside.rocks*', '*libreddit.strongthany.cc*', '*libreddit.database.red*', '*libreddit.privacy.com.de*', '*libreddit.domain.glass*', '*libreddit.sugoma.tk*', '*libreddit.jamiethalacker.dev*', '*reddit.artemislena.eu*', '*r.nf*', '*libreddit.some-things.org*', '*reddit.stuehieyr.com*', '*lr.mint.lgbt*', '*libreddit.igna.rocks*', '*libreddit.autarkic.org*', '*libreddit.flux.industries*', '*libreddit.drivet.xyz*', '*lr.oversold.host*', '*libreddit.de*', '*libreddit.pussthecat.org*', '*libreddit.mutahar.rocks*', '*libreddit.northboot.xyz*', '*leddit.xyz*', '*de.leddit.xyz*', '*lr.cowfee.moe*', '*libreddit.hu*', '*libreddit.totaldarkness.net*', '*libreddit.esmailelbob.xyz*', '*lr.vern.cc*', '*libreddit.nl*', '*lr.stilic.ml*', '*reddi.tk*', '*libreddit.bus-hit.me*', '*libreddit.datatunnel.xyz*', '*libreddit.crewz.me*', '*r.walkx.org*', '*libreddit.kylrth.com*', '*libreddit.yonalee.eu*', '*libreddit.winscloud.net*', '*libreddit.tiekoetter.com*', '*reddit.rtrace.io*', '*libreddit.lunar.icu*', '*libreddit.privacydev.net*', '*libreddit.notyourcomputer.net*', '*r.ahwx.org*', '*bob.fr.to*', '*reddit.beparanoid.de*', '*libreddit.dcs0.hu*', '*reddit.dr460nf1r3.org*', '*rd.jae.su*', '*libreddit.mha.fi*', '*libreddit.foss.wtf*', '*libreddit.encrypted-data.xyz*', '*libreddit.eu.org*', '*l.opnxng.com*', '*safereddit.com*', '*libreddit.projectsegfau.lt*', '*libreddit.bus-hit.me*', '*reddit.invak.id*', '*redlib.catsarch.com*', '*reddit.idevicehacked.com*', '*redlib.freedit.eu*', '*redlib.perennialte.ch*', '*redlib.tux.pizza*', '*redlib.vimmer.dev*', '*libreddit.privacydev.net*', '*lr.n8pjl.ca*', '*reddit.owo.si*', '*redlib.ducks.party*', '*red.ngn.tf*', '*redlib.dnfetheus.xyz*', '*redlib.cow.rip*', '*libreddit.eu.org*', '*r.darrennathanael.com*', '*redlib.kittywi.re*', '*redlib.privacyredirect.com*'],
    'lichess.css': ['*lichess.org*'],
    'lingva.css': ['*lingva.ml*', '*translate.plausibility.cloud*', '*lingva.lunar.icu*', '*translate.projectsegfau.lt*', '*lingva.garudalinux.org*'],
    'linkedin.css': ['*www.linkedin.com*'],
    'listenbrainz.css': ['*listenbrainz.org*'],
    'lobste.rs.css': ['*lobste.rs*'],
    'mastodon.css': ['*mastodon.social*', '*social.catppuccin.com*', '*fosstodon.org*'],
    'mdbook.css': ['*rust-lang.github.io*', '*doc.rust-lang.org*', '*rust-book.cs.brown.edu*', '*rustc-dev-guide.rust-lang.org*', '*forge.rust-lang.org*', '*lang-team.rust-lang.org*', '*doc.redox-os.org*', 'https://lukaswirth.dev/tlborm/*'],
    'mdn.css': ['*developer.mozilla.org*', '*interactive-examples.mdn.mozilla.net*'],
    'microsoft-word.css': ['*live.com*'],
    'migadu-webmail.css': ['*webmail.migadu.com*'],
    'minesweeper.css': ['*minesweeper.online*'],
    'modrinth.css': ['*modrinth.com*'],
    'namemc.css': ['*namemc.com*'],
    'neovim.io.css': ['*neovim.io*'],
    'nitter.css': ['*nitter.net*', '*nitter.unixfox.eu*', '*nitter.42l.fr*', '*nitter.fdn.fr*', '*nitter.1d4.us*', '*nitter.kavin.rocks*', '*nitter.namazso.eu*', '*nitter.hu*', '*bird.trom.tf*', '*nitter.it*', '*twitter.censors.us*', '*nitter.grimneko.de*', '*n.hyperborea.cloud*', '*nitter.ca*', '*twitter.076.ne.jp*', '*nitter.mstdn.social*', '*nitter.fly.dev*', '*nitter.weiler.rocks*', '*nitter.sethforprivacy.com*', '*nttr.stream*', '*nitter.tiekoetter.com*', '*nitter.spaceint.fr*', '*nitter.privacy.com.denitter.mastodon.pro*', '*nitter.notraxx.chnitter.poast.org*', '*nitter.bird.froth.zone*', '*nitter.dcs0.hu*', '*twitter.beparanoid.de*', '*n.ramle.be*', '*nitter.cz*', '*nitter.privacydev.net*', '*tweet.lambda.dance*', '*nitter.kylrth.com*', '*nitter.oishi-ra.men*', '*nitter.foss.wtf*', '*nitter.priv.pw*', '*t.com.sb*', '*xcancel.com*', '*nitter.poast.org*'],
    'nixos-manual.css': ['https://nixos.org/manual/*', 'https://nix-darwin.github.io/nix-darwin/manual/*'],
    'nixos-search.css': ['*search.nixos.org*'],
    'npm.css': ['*www.npmjs.com*'],
    'ollama.css': ['*ollama.com*'],
    'openmediavault.css': ['*openmediavault.example.com*'],
    'paste.rs.css': ['*paste.rs*'],
    'perplexity.css': ['*perplexity.ai*'],
    'phanpy.css': ['*phanpy.social*'],
    'picrew.css': ['*picrew.me*'],
    'pinterest.css': [r'^https?:\\/\\/(www|[a-z]{2}).pinterest.(com(.(au|mx))?|co(.(uk|kr))?|at|ca|ch|cl|de|dk|es|fr|ie|it|jp|nz|ph|pt|ru|se)\\/.*'],
    'planet-minecraft.css': ['*planetminecraft.com*'],
    'poe.css': ['https://poe.com*'],
    'porkbun.css': ['*porkbun.com*'],
    'pronouns.cc.css': ['*pronouns.cc*'],
    'pronouns.page.css': ['*pronouns.page*', '*pronomen.net*', '*pronombr.es*', '*pronomejo.net*', '*fornovn.fo*', '*pronoms.fr*', '*pronom.it*', '*zaimki.pl*'],
    'proton.css': [r'https://(account|mail|drive|calendar|lumo).proton.me/.*$'],
    'pypi.css': ['*pypi.org*'],
    'pythonanywhere.css': ['*www.pythonanywhere.com*', '*eu.pythonanywhere.com*', '*blog.pythonanywhere.com*'],
    'quizlet.css': ['*quizlet.com*'],
    'raindrop.css': ['*app.raindrop.io*'],
    'react.dev.css': ['*react.dev*'],
    'reddit.css': ['*reddit.com*'],
    'regex101.css': ['*regex101.com*'],
    'rentry.co.css': ['*rentry.org*', '*rentry.co*', '*export3.rentry.co*', 'https://rentry.co/static/*', r'https?://rentry\\.(co|org)/.+/(raw|exists)'],
    'scalar.css': ['*scalar.com*'],
    'searchix.css': ['*searchix.ovh*'],
    'searxng.css': ['*search.bus-hit.me*', '*search.inetol.net*'],
    'seventv.css': ['*7tv.app*', '*twitch.tv*'],
    'shinigami-eyes.css': ['*facebook.com*', '*youtube.com*', '*reddit.com*', '*twitter.com*', '*x.com*', '*medium.com*', '*disqus.com*', '*tumblr.com*', '*wikipedia.org*', '*rationalwiki.org*', '*cohost.org*', '*bsky.app*', '*anarchism.space*', '*aus.social*', '*c.im*', '*chaos.social*', '*eightpoint.app*', '*eldritch.cafe*', '*fosstodon.org*', '*hachyderm.io*', '*infosec.exchange*', '*kolektiva.social*', '*mas.to*', '*masto.ai*', '*chaosfem.tw*', '*mastodon.art*', '*mastodon.cloud*', '*mastodon.green*', '*mastodon.ie*', '*mastodon.nz*', '*mastodon.online*', '*mastodon.scot*', '*mastodon.social*', '*mastodon.world*', '*mastodon.xyz*', '*mastodonapp.uk*', '*meow.social*', '*mstdn.ca*', '*mstdn.jp*', '*mstdn.social*', '*octodon.social*', '*ohai.social*', '*pixelfed.social*', '*queer.party*', '*sfba.social*', '*social.transsafety.network*', '*tech.lgbt*', '*techhub.social*', '*toot.cat*', '*toot.community*', '*toot.wales*', '*vulpine.club*', '*wandering.shop*', '*lgbtqia.space*', '*threads.net*', '*duckduckgo.com*', '*bing.com*', '*google.ar*', '*google.at*', '*google.be*', '*google.ca*', '*google.ch*', '*google.co.uk*', '*google.com*', '*google.de*', '*google.dk*', '*google.es*', '*google.fi*', '*google.fr*', '*google.is*', '*google.it*', '*google.no*', '*google.pt*', '*google.se*'],
    'snapchat-web.css': ['https://www.snapchat.com/web*'],
    'spotify-web.css': ['*open.spotify.com*'],
    'stack-overflow.css': ['*stackoverflow.com*', '*stackexchange.com*', '*serverfault.com*', '*superuser.com*', '*mathoverflow.net*', '*askubuntu.com*', '*stackapps.com*'],
    'startpage.css': ['*startpage.com*'],
    'status.cafe.css': ['*forum.status.cafe*', r'https://status\\.cafe/(?!users).*'],
    'stylus.css': ['moz-extension://*', 'chrome-extension://*'],
    'substack.css': ['*substack.com*'],
    'syncthing.css': [r'https?://(%s)/.*', r', @urls), ', r',', r', ', r'|', r', ', r'g', r'), ', r' ', r', ', r', ', r'g'],
    'tabnews.css': ['*tabnews.com.br*'],
    'tldraw.css': ['*tldraw.com*'],
    'trinket.css': ['*trinket.io*'],
    'tuta.css': ['*app.tuta.com*', '*mail.tutanota.com*'],
    'twitch.css': ['*twitch.tv*', '*dashboard.twitch.tv*', '*dev.twitch.tv*', 'https://discuss.dev.twitch.com/embed/topics*'],
    'twitter.css': ['*twitter.com*', '*x.com*', '*api.twitter.com*', '*api.x.com*', '*twitter.com*', '*x.com*'],
    'vercel.css': ['*vercel.com*', '*nextjs.org*', '*nextjs.org*'],
    'vikunja.css': ['*try.vikunja.io*'],
    'web.dev.css': ['https://web.dev*'],
    'whatsapp-web.css': ['*web.whatsapp.com*'],
    'wiki.nixos.org.css': ['*wiki.nixos.org*'],
    'wikipedia.css': ['*wikipedia.org*', '*wiktionary.org*', '*www.mediawiki.org*', '*auth.wikimedia.org*', '*wikiversity.org*', '*wikisource.org*', '*meta.wikimedia.org*', '*wikidata.org*', '*wikibooks.org*', '*species.wikimedia.org*', '*commons.wikimedia.org*', '*wikivoyage.org*', '*wikinews.org*', '*wikiquote.org*'],
    'wikiwand.css': ['*wikiwand.com*'],
    'youtube.css': ['*youtube.com*', '*m.youtube.com*', 'https://studio.youtube.com*'],
    'zen-browser-docs.css': ['*zen-browser.app*'],
}
