# An example configuration file for MPD.
# Read the user manual for documentation: http://www.musicpd.org/doc/user/

# ---------
# Locations
# ---------

# Music :3
# music_directory		"$XDG_MUSIC_DIR"
music_directory	        "~/Music"

# MPD playlist location
# playlist_directory    "$XDG_CONFIG_HOME/mpd/playlists"
playlist_directory      "~/.config/mpd/playlists"

# Database cache
db_file			        "$XDG_CACHE_HOME/mpd/database"
#db_file			    "~/.mpd/database"

# ---------------
# General options
# ---------------

# Address
# ^ For network
# bind_to_address		"any"

# ^ And for Unix Socket
# bind_to_address		"$XDG_RUNTIME_DIR/mpd/socket"
# bind_to_address		"~/.config/mpd/socket"

# ^ Port
port				    "6600"

# Look for changes in music and update database with
auto_update	            "yes"

# --------
# Symlinks
# --------

# Use symlinks outside the music directory
# follow_outside_symlinks   "yes"

# Use symlinks within the music directory
# follow_inside_symlinks	"yes"

# -----------
# Permissions
# -----------

# Password for the mpd profile
# password              "password@read,add,control,admin"

# permission for non logged in user
# default_permissions   "read,add,control,admin"

# -----
# Input
# -----

# allows getting songs through links
input {
        plugin "curl"
}

# ------------
# Audio Output
# ------------

# There are lots of way to setup audio outputs, reffer to the documentation if pipewire doesnt fit

# A simple pipewire output
audio_output {
	type "pipewire"
	name "PipeWire Sound Server"
}

# Prints audio data to a file for rmpc to use for cava
audio_output {
   type   "fifo"
   name   "my_fifo"
   path   "/tmp/mpd.fifo"
   format "44100:16:2"
}
